# Practical 1

#### Run the 2 cells below for Google Colab

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
! mkdir ~/.kaggle
! mkdir data
! cp "/content/drive/MyDrive/kaggle.json" ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets download -d pablotab/mnistpklgz
! unzip mnistpklgz.zip -d data

 65% 21.0M/32.1M [00:00<00:00, 30.7MB/s]
100% 32.1M/32.1M [00:00<00:00, 80.6MB/s]
Archive:  mnistpklgz.zip
  inflating: data/mnist.pkl          
  inflating: data/mnist.pkl.gz       


### Shrey Viradiya
### 18BCE259

In [3]:
import numpy
import sklearn.metrics
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import pickle

In [4]:
def load_data():
    with open('./data/mnist.pkl', 'rb') as f: 
        training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
    return (training_data, validation_data, test_data)

In [5]:
training_data, validation_data, test_data = load_data()

In [6]:
X_train, y_train = training_data
X_valid, y_valid = validation_data
X_test, y_test = test_data
X_train = X_train/255.
X_valid = X_valid/255.
X_test = X_test/255.

In [7]:
print(X_train.shape, y_train.shape)
print(X_valid.shape, y_valid.shape)
print(X_test.shape, y_test.shape)

(50000, 784) (50000,)
(10000, 784) (10000,)
(10000, 784) (10000,)


In [8]:
MLPClassifier?

In [9]:
mlp =  MLPClassifier(max_iter=100)
parameter_space = {
    'hidden_layer_sizes': [(10,30,10),(20,)],
    'activation': ['tanh', 'relu'],
    'solver': ['adam', ],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}

In [10]:
clf = GridSearchCV(mlp, parameter_space, n_jobs=-1, cv=5)
clf.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


GridSearchCV(cv=5, error_score=nan,
             estimator=MLPClassifier(activation='relu', alpha=0.0001,
                                     batch_size='auto', beta_1=0.9,
                                     beta_2=0.999, early_stopping=False,
                                     epsilon=1e-08, hidden_layer_sizes=(100,),
                                     learning_rate='constant',
                                     learning_rate_init=0.001, max_fun=15000,
                                     max_iter=100, momentum=0.9,
                                     n_iter_no_change=10,
                                     nesterovs_momentum=True, power_t=0.5,
                                     random_state...
                                     solver='adam', tol=0.0001,
                                     validation_fraction=0.1, verbose=False,
                                     warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'activation': ['ta

In [11]:
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (10, 30, 10), 'learning_rate': 'constant', 'solver': 'adam'}


In [12]:
prediction = clf.predict(X_test)

In [13]:
print(sklearn.metrics.accuracy_score(prediction, y_test))
print(sklearn.metrics.classification_report(prediction, y_test))
print(sklearn.metrics.confusion_matrix(prediction, y_test))

0.9299
              precision    recall  f1-score   support

           0       0.97      0.96      0.96       990
           1       0.98      0.98      0.98      1142
           2       0.91      0.94      0.92      1000
           3       0.93      0.88      0.90      1063
           4       0.96      0.90      0.93      1044
           5       0.88      0.88      0.88       893
           6       0.94      0.95      0.95       952
           7       0.93      0.95      0.94      1010
           8       0.90      0.91      0.90       960
           9       0.88      0.94      0.91       946

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 949    0   10    2    0    7    9    0    2   11]
 [   0 1117    1    2    1    1    3    9    5    3]
 [   1    3  938   19    5    5   11   13    5    0]
 [   1    4   25  938    1   44    0   16   24   10]
 [   4    0    7    1 