# Practical 1

### Shrey Viradiya
### 18BCE259

In [1]:
import numpy
import sklearn.metrics
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import pickle

In [2]:
def load_data():
    with open('./data/mnist.pkl', 'rb') as f: 
        training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
    return (training_data, validation_data, test_data)

In [3]:
training_data, validation_data, test_data = load_data()

In [4]:
X_train, y_train = training_data
X_valid, y_valid = validation_data
X_test, y_test = test_data
X_train = X_train/255.
X_valid = X_valid/255.
X_test = X_test/255.

In [5]:
print(X_train.shape, y_train.shape)
print(X_valid.shape, y_valid.shape)
print(X_test.shape, y_test.shape)

(50000, 784) (50000,)
(10000, 784) (10000,)
(10000, 784) (10000,)


In [6]:
MLPClassifier?

Init signature:
MLPClassifier(
    hidden_layer_sizes=(100,),
    activation='relu',
    *,
    solver='adam',
    alpha=0.0001,
    batch_size='auto',
    learning_rate='constant',
    learning_rate_init=0.001,
    power_t=0.5,
    max_iter=200,
    shuffle=True,
    random_state=None,
    tol=0.0001,
    verbose=False,
    warm_start=False,
    momentum=0.9,
    nesterovs_momentum=True,
    early_stopping=False,
    validation_fraction=0.1,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-08,
    n_iter_no_change=10,
    max_fun=15000,
)
Docstring:     
Multi-layer Perceptron classifier.

This model optimizes the log-loss function using LBFGS or stochastic
gradient descent.

.. versionadded:: 0.18

Parameters
----------
hidden_layer_sizes : tuple, length = n_layers - 2, default=(100,)
    The ith element represents the number of neurons in the ith
    hidden layer.

activation : {'identity', 'logistic', 'tanh', 'relu'}, default='relu'
    Activation function for the hidden layer.

  

In [7]:
mlp =  MLPClassifier(max_iter=100)
parameter_space = {
    'hidden_layer_sizes': [(10,30,10),(20,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}

In [8]:
clf = GridSearchCV(mlp, parameter_space, n_jobs=-1, cv=5)
clf.fit(X_train, y_train)

In [ ]:
print('Best parameters found:\n', clf.best_params_)

In [9]:
prediction = clf.predict(X_test)

In [10]:
print(sklearn.metrics.accuracy_score(prediction, y_test))
print(sklearn.metrics.classification_report(prediction, y_test))
print(sklearn.metrics.confusion_matrix(prediction, y_test))

0.9065
[[ 966    0   20   12    2   24   13    5   16   19]
 [   0 1086    0    3    0    2    1   10    5    9]
 [   2   11  944   39    3    2    2   37    4    0]
 [   1    2    6  824    0   14    0    8    7    3]
 [   2    2   10    8  951   11   11   20   14  138]
 [   2    2    1   59    0  782   10    1   35    9]
 [   6    5   22    5   13   25  916    0   19    0]
 [   1    1   11    8    2    5    0  934    2   16]
 [   0   26   18   47    3   22    5    1  861   14]
 [   0    0    0    5    8    5    0   12   11  801]]
